name: Build and Push Docker Multi-Arch Image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download exllamav2
        uses: robinraju/release-downloader@v1
        with:
          repository: 'turboderp-org/exllamav2'
          tag: 'v0.2.7'
          fileName: 'exllamav2-0.2.7+cu121.torch2.5.0-cp312-cp312-linux_x86_64.whl'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/yue-exllamav2-ui:latest
